version: '3'

services:
  kucoin-bot:
    build: .
    ports:
      - "8000:8000"  # API
      - "8050:8050"  # Dashboard
    environment:
      - KUCOIN_API_KEY=${KUCOIN_API_KEY}
      - KUCOIN_API_SECRET=${KUCOIN_API_SECRET}
      - KUCOIN_API_PASSPHRASE=${KUCOIN_API_PASSPHRASE}
      - API_USERNAME=${API_USERNAME:-admin}
      - API_PASSWORD=${API_PASSWORD:-password}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-jwt}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
    restart: unless-stopped
